# Generated by Django 2.0.4 on 2018-05-04 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(db_index=True, max_length=30)),
                ('car_model', models.CharField(db_index=True, max_length=30)),
                ('body_type', models.CharField(choices=[('s', 'sedan'), ('c', 'coupe'), ('h', 'hatch'), ('w', 'wagon'), ('su', 'suv'), ('u', 'ute'), ('m', 'mini van'), ('ca', 'cabriolet')], max_length=2)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('kilometres', models.PositiveIntegerField(db_index=True)),
                ('reg_expirity', models.DateField()),
                ('reg_number', models.CharField(max_length=10)),
                ('transmission', models.CharField(choices=[('a', 'automatic drive'), ('m', 'manual')], max_length=1)),
                ('train', models.CharField(choices=[('a', 'AWD'), ('f', 'FWD'), ('r', 'RWD')], max_length=1)),
                ('fuel_type', models.CharField(choices=[('p', 'petrol'), ('d', 'diesel'), ('e', 'electricity')], max_length=1)),
                ('color', models.CharField(default='white', max_length=20)),
                ('price', models.PositiveIntegerField(db_index=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('new_field', models.CharField(max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
