# Generated by Django 2.0.4 on 2018-05-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='equipment',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='postcode',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='state',
            field=models.CharField(blank=True, choices=[('nsw', 'New South Wales'), ('qld', 'Queensland'), ('sa', 'South Australia'), ('tas', 'Tasmania'), ('vic', 'Victoria'), ('wa', 'Western Australia')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('s', 'Sedan'), ('c', 'Coupe'), ('h', 'Hatch'), ('w', 'Wagon'), ('su', 'SUV'), ('u', 'Ute'), ('m', 'Mini van'), ('ca', 'Cabriolet')], max_length=2),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('p', 'Petrol'), ('d', 'Diesel'), ('e', 'Electric'), ('pe', 'Petrol-Electric'), ('pl', 'Petrol/LPG Autogas'), ('l', 'LPG Autogas')], max_length=2),
        ),
        migrations.AlterField(
            model_name='car',
            name='train',
            field=models.CharField(choices=[('a', 'All Wheel Drive'), ('f', 'Forward Wheel Drive'), ('r', 'Rear Wheel Drive')], max_length=1),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('a', 'Automatic drive'), ('m', 'Manual')], max_length=1),
        ),
    ]
